#!/bin/bash

# Environment Setup Script for Contract Management System
# This script helps set up the environment configuration files

set -e

echo "🔧 Setting up Contract Management System Environment..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if config.env exists
if [ ! -f "config.env" ]; then
    print_error "config.env not found! Please create it from config.env.example"
    exit 1
fi

# Create secrets.env.local if it doesn't exist
if [ ! -f "secrets.env.local" ]; then
    print_status "Creating secrets.env.local from secrets.env template..."
    cp secrets.env secrets.env.local
    print_warning "Please edit secrets.env.local with your actual secret values!"
    print_warning "This file should NEVER be committed to version control."
else
    print_success "secrets.env.local already exists"
fi

# Create .env file for Docker Compose (combines config.env and secrets.env.local)
print_status "Creating .env file for Docker Compose..."
{
    echo "# Combined environment configuration for Docker Compose"
    echo "# Generated by setup-environment.sh"
    echo ""
    cat config.env
    echo ""
    echo "# Secrets (loaded from secrets.env.local)"
    if [ -f "secrets.env.local" ]; then
        cat secrets.env.local
    else
        print_warning "secrets.env.local not found, using secrets.env template"
        cat secrets.env
    fi
} > .env

print_success "Environment setup complete!"

echo ""
echo "📋 Next Steps:"
echo "1. Edit secrets.env.local with your actual secret values"
echo "2. Edit config.env if you need to change any configuration"
echo "3. Run: docker-compose -f docker-compose.dev.yml up -d"
echo ""
echo "🔒 Security Notes:"
echo "- secrets.env.local is in .gitignore and will not be committed"
echo "- .env is in .gitignore and will not be committed"
echo "- Only config.env.example and secrets.env are tracked in git"
echo ""
echo "🧪 Test your configuration:"
echo "docker-compose -f docker-compose.dev.yml config"
