apiVersion: v1
kind: PersistentVolume
metadata:
  name: ***REMOVED-DB_PASSWORD***-pv
  namespace: contract-management
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/***REMOVED-DB_PASSWORD***
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ***REMOVED-DB_PASSWORD***-pvc
  namespace: contract-management
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi 